spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbbDatabase?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: sbbDatabase
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  spring:
    devtools:
      livereload:
        # livereload 서버 켜기
        enabled: true
      remote:
        restart:
          # 원격 재시작 활성화
          enabled: true
